version: "3.7"
services:
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource

  influxdb:
    image: influxdb
    restart: always
    ports:
      - 8086:8086
      - 8089:8089/udp
    networks:
      - monitoring
    volumes:
      - influx-data:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    command:
      -config /etc/influxdb/influxdb.conf

networks:
  monitoring:

volumes:
  grafana-data: {}
  influx-data: {}